#!/usr/bin/env ruby

arg, *scope = ARGV
arg ||= 'fix'
scope = "(#{scope.join(' ')})" if scope.length > 0
arg = [arg, scope].join('')
arg += ': ' if arg.length > 0

res = ''

begin
	print "Summary (#{arg.strip.gsub(':', '')}): "
	res = STDIN.gets.strip

	return if res.length == 0

	print 'Description: '
	body = STDIN.gets.strip
	res += "\n\n#{body}" if body.length > 0
	print 'Footer (breaking change): '
	foot = STDIN.gets.strip
	res += "\n\nBREAKING CHANGE: #{foot}" if foot.length > 0
	arg.gsub!(':', '!:') if foot.length > 0
rescue Interrupt
	puts "\naborted"
	return
end

return if (res.length == 0)

run = %Q(git commit -am "#{(arg+res).gsub('"', '\"')}")
puts " → #{run}"
system run
