#!/usr/bin/env ruby


class String
  # colorization
  def colorize(color_code)
    "\e[#{color_code}m#{self}\e[0m"
  end

  def red
    colorize(31)
  end

  def green
    colorize(32)
  end

  def yellow
    colorize(33)
  end

  def blue
    colorize(34)
  end

  def pink
    colorize(35)
  end

  def light_blue
    colorize(36)
  end
end

Dir.foreach('.') do |d|
  next unless File.directory? d
  next if d == '.' || d == '..' || d.start_with?('.')
  Dir.chdir(d) do |directory|
    puts "Executing " + ARGV.join(' ').green + " in " + directory
    system ARGV.join ' '
  end
end

